name: CI/CD - Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi --no-root

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Remplace par ton pseudo et le nom de ton Space
        git remote add hf https://FLORIANSC:$HF_TOKEN@huggingface.co/spaces/FLORIANSC/agritech-interface
        git push --force hf main